### ISSUE TITLE
GitHub repo creation not working on mac OS

### ISSUE THREAD

**Issue by vineetmimrot** [microsoft/vscode-deploy-azure#120]
It fails with error: 
error: unknown switch `U' usage: git remote add [<options>] <name> <url> -f, --fetch fetch the remote branches --tags import all tags and associated objects when fetching or do not fetch any tag at all (--no-tags) -t, --track <branch> branch(es) to track -m, --master <branch> master branch --mirror[=(push|fetch)] set up remote as a mirror to push to or fetch from

**Comment by JA-04** [comment]
Thanks for pointing it out. The issue has been fixed now.
