### ISSUE TITLE
[Suggestion][VSCode/GitHub] GitHub PAT token should be asked after asking about all the Azure resource details

### ISSUE THREAD

**Issue by vineetmimrot** [microsoft/vscode-deploy-azure#122]
@bishal-pdMSFT @kanika1894 Can we ask all the repo details first and then ask Azure details like Subscription. Currently it is mixed and match. 1st subscription then github pat then azure resource details etc

**Comment by anuragc617** [comment]
@vineetmimrot github PAT token is asked before azure resource details to do the repository analysis and then get the templates.

**Comment by kanika1894** [comment]
The order of inputs in now changed. First we ask github PAT, and then all azure related details are asked together.
