### ISSUE TITLE
Azure pipelines creation failed for AspNet webapp 

### ISSUE THREAD

**Issue by vineetmimrot** [microsoft/vscode-deploy-azure#123]
https://dev.azure.com/vineetpc/AspNetWebApp/_build/results?buildId=706&view=results

![image](https://user-images.githubusercontent.com/4174297/86249707-45164a80-bbcd-11ea-9c03-87ad8cda872f.png)

**Comment by kanika1894** [comment]
Issue was in the yaml template.
This is fixed now. Part of the PR : https://github.com/microsoft/vscode-deploy-azure/pull/118
