### ISSUE TITLE
Cannot read property 'session' of undefined (v1.1.1)

### ISSUE THREAD

**Issue by issacnitin** [microsoft/vscode-deploy-azure#137]
![Capture](https://user-images.githubusercontent.com/4218887/89547270-2c7bfe80-d823-11ea-9b8c-06744fc4ec05.PNG)

Casually checking in 😃 
Happens after logging in to Azure

**Comment by vineetmimrot** [comment]
Thanks for reporting man, @Kanika<mailto:Kanika.Pasrija@microsoft.com> can you please look into it. 😊
Can you please tell which version of Azure account extension you are using?

--
Best Regards,
Vineet Mimrot

**Comment by bishal-pdMSFT** [comment]
Thanks @issacnitin :)
@kanika1894 please check thia

**Comment by issacnitin** [comment]
> Thanks for reporting man, @kanika<mailto:Kanika.Pasrija@microsoft.com> can you please look into it. 😊 Can you please tell which version of Azure account extension you are using?
> […](#)
> -- Best Regards, Vineet Mimrot From: Nitin Issac Joy <notifications@github.com> Date: Thursday, 6 August 2020 at 8:27 PM To: microsoft/vscode-deploy-azure <vscode-deploy-azure@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [microsoft/vscode-deploy-azure] Cannot read property 'session' of undefined (v1.1.1) (#137) [Capture]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F4218887%2F89547270-2c7bfe80-d823-11ea-9b8c-06744fc4ec05.PNG&data=02%7C01%7CVineet.Mimrot%40microsoft.com%7Ccc31b166822c4d27c74308d83a191704%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637323226723266964&sdata=e52V1mcLDofkVM3yDHYJZ0BzlqxAjU23x2VETesFqDg%3D&reserved=0> Casually checking in 😄 Happens after logging in to Azure — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode-deploy-azure%2Fissues%2F137&data=02%7C01%7CVineet.Mimrot%40microsoft.com%7Ccc31b166822c4d27c74308d83a191704%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637323226723276960&sdata=gZB%2FwoVfTvlBLoIbK0flEdnoNfgve98vazVT6AhMYSA%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA73DWODRNHA2I2GU7E4LGLR7LAG5ANCNFSM4PWVRPQQ&data=02%7C01%7CVineet.Mimrot%40microsoft.com%7Ccc31b166822c4d27c74308d83a191704%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637323226723276960&sdata=gEW96SyUo6Z25n3U6uWRcbZM3w0BNRXYrOg3kSDjx7o%3D&reserved=0>.

v0.8.11
Also, it's asking me to login every time I restart vscode

**Comment by kanika1894** [comment]
I'll look into this

**Comment by vineetmimrot** [comment]
@issacnitin I believe this issue occurred only for the first time, from the second time you were able to setup pipeline. Can you please confirm?

**Comment by issacnitin** [comment]
> @issacnitin I believe this issue occurred only for the first time, from the second time you were able to setup pipeline. Can you please confirm?

Second time in same window - yes
But when I restarted vscode, it was asking for sign-in again. This issue is not reproable any more though

**Comment by vineetmimrot** [comment]
fixed and deployed
