### ISSUE TITLE
Too many failures in last 3 weeks: Couldn't get repository details. 

### ISSUE THREAD

**Issue by vineetmimrot** [microsoft/vscode-deploy-azure#139]
Couldn't get repository details. Ensure your repo is hosted on [Azure Repos](https://docs.microsoft.com/azure/devops/repos/get-started) or [GitHub](https://guides.github.com/activities/hello-world/).

https://dataexplorer.azure.com/clusters/ddtelvscode/databases/VSCodeExt?query=H4sIAAAAAAAAA31TTU9qMRDd8ytqN0KiYuLSYPLCM083hniNLk29HbBa2mamBTHG3+4UvJcK17fsnI85004tREFRYYxmDmIk1Mz3z0714LxnGbmhVNdANE3239WDx9ep9Utm3arl5QJcpPtq7DVcvsXeh1g+A4KoABeAd+zGtvMgLrb2LWejqtjYeHetxcFIHJKfw72yCU6oqR+2Am4ALhdvVE45ElK9J4RjDcH6ldzycqhOzrD2bmpmuVCbWh8HE8AaB1kL2V2LgD4QDxcUEjy+kHf9CZcAowEabHkIwTN3YTQg06OniMbN+mv9SYkWohef0MHK6H1FCxX0OiHyKImAiSHFfdUu40dASrZDsqnvd6kihF8bEIOFhNIT1WhC5MfoGuYnXgibC1cWQelV+xwdHr9SCztA9Mg7RmoG+w4lOugNh81+/CfEp5ARE+/Dlr0zK2+pLOHy9g6M+xR9OX6G+vXaTZrlOpJjbhThj9O3qSgLOeHAzXnN4R5SHMm/hoJVq41Mt4pyiO/nzXGq/D1Bg5bnvR04DzRVxq6xzn/8BSuDxNX7AwAA

let starttime = ago(30d);
let NsuccessfulGHWorkflow = RawEventsVSCodeExt
| where ServerTimestamp > starttime
| where VSCodeSessionId != 'someValue.sessionId'
| where ExtensionName == "azure-deploy"
| where EventName == "azure-deploy/configure-cicd-pipeline"
| extend props = parse_json(Properties)
| extend repoprovider = tostring(props.repoprovider)
| extend journeyid = tostring(props.journeyid)
| extend currentuserinput = tostring(props.currentuserinput)
| extend result = tostring(props.result)
| extend currentStep = tostring(props.currentstep)
| extend subscriptionid = tostring(props.subscriptionid)
| extend pipelinealreadyconfigured = tostring(props.pipelinealreadyconfigured)
| extend errormessage = tostring(props.errormessage)
//| where pipelinealreadyconfigured =~ "true"
//| where subscriptionid != ""
//| where currentStep !in~ ("CheckInPipeline","CreateAndRunPipeline", "PostPipelineCreation" ,"DisplayCreatedPipeline")
| where result =~ "failed";
NsuccessfulGHWorkflow

@kanika1894 Please check this issue.

**Comment by kanika1894** [comment]
For the logs having error message "Couldn't get respository details", the failure is because repoProvider isn't even GitHub or Azure.
The repo providers for these errors are : GitLab/Bigbucket/Other. I don't think we are supporting these providers, that's why such errors.

**Comment by vineetmimrot** [comment]
Please double check, the ratio of these failures are very high. So I doubt, people are using other than GitHub, ADO or local git scenario. We should also check the repo analysis logs. Please try to raise this string fix PR.

--
Best Regards,
Vineet Mimrot

**Comment by kanika1894** [comment]
PR for better insights to handle different repo provider scenarios : https://github.com/microsoft/vscode-deploy-azure/pull/140

**Comment by kanika1894** [comment]
Closing as this error is whitelisted
