### ISSUE TITLE
Failed to Render

### ISSUE THREAD

**Issue by isaacrlevin** [microsoft/vscode-deploy-azure#195]
Tried deploying a .NET 5 Application to App Service and got the following error

> Pipeline provisioning job failed with error: 'Error=Failed to render: Evaluation error: Helper 'beginsWith' called with wrong number of arguments, needed 5 but got 0 Current node: Expr{Path:Path{Original:'beginsWith', Pos:3}, Pos:0}, Message=Mustache parsing failed'

No other errors in logs

Here is a repo to test

https://github.com/isaacrlevin/.NET-Conf-Demos/tree/main/AppService

**Comment by kanika1894** [comment]
Hey @isaacrlevin ,
After providing the Github PAT, when it gives a list of pipeline templates, which one did you choose?

**Comment by isaacrlevin** [comment]
ASP.NET web app to App Service

**Comment by kanika1894** [comment]
@isaacrlevin Thanks for the information. Looking into it.

**Comment by ashwinsangem** [comment]
@isaacrlevin, thanks a lot for your patience. The issue has now been fixed.
