### ISSUE TITLE
using python workflow from template service causes unwanted manifest files to be added to web app folders

### ISSUE THREAD

**Issue by vivishno** [microsoft/vscode-deploy-azure#204]
Description-
Template service has been updated with python support for linux web app.
PR [link](https://github.com/github/cicd-workflow-templates-service/pull/121/files)
vs code-deploy-azure repo was configured locally to fetch the newly added template for python locally. Using these changes
the template got fetched and was committed to repo successfully. But after the workflow gets committed oryx build manifest files are also getting added to the web app folder structure. These files are not being added by workflow run and also cause the run to fail.

Steps  -
- Run template service locally
- Run provisioning service locally
- configure vscode-deploy-azure repo with given patch [link to patch](https://drive.google.com/file/d/1sn-IQ2Tb1xWWD91cKS_Eem9lPv-gbGs_/view?usp=sharing)
-  Build and run vs code repo and use deploy to azure option -"command+shift+p"
- select a python repo- sample [repo](https://github.com/vivishno/flask-tutorial)
- from the list of template options select "Python to App Service" (the newly added template in template service)
- select rest options as required. python version(select any), startup command(default empty)
- the workflow gets committed succsessfully.
- Check the web app folder structure by hitting the url of the web app.
- We can see extra files being added to the structure which are not being caused by workflow.
- **To confirm that this is not a workflow issue and vs code specific issue following steps were taken**
      -> The workflow in template service was shortened to just checkout action. Expectation here is that it won't run anything and app folder will be empty.But still these files were being added after committing.[video link](https://drive.google.com/file/d/1kt3hfxnz7x8Lrl9N7DsbLY4FvcKRJleY/view?usp=sharing)
-> the same process was done using postman where workflow was fetched and committed by making call to provisioning service apis. In this case workflow got committed as before and also no extra files were added .

We suspect that vs code is tweaking some properties in web app causing these files to be added .This requires More investigation.

**Comment by vivishno** [comment]
app settings screenshot[link](https://drive.google.com/file/d/1DCQWW2EVqknq0-Iyiz1jpr_Sh8t5Yiia/view?usp=sharing)

**Comment by kanika1894** [comment]
@tiwarishub 
Can you have a look at this?
I guess first step will be identify at what step are these files getting created, then we can see how to proceed.

**Comment by kanika1894** [comment]
@tiwarishub any updates on this?

**Comment by tiwarishub** [comment]
@kanika1894, I had a discussion with @vivishno about this. As currently, this flow is not using provisioning service and he is facing the issues only when VS code is doing provisioning. I am working on one story which will move GitHub repo's web app flows(Simple web app and python) will not use local provisioning and will use provisioning service and I will notify here to check once if this issue will be still there

**Comment by kanika1894** [comment]
Hoping that this gets handled in your story @tiwarishub , will close this for now.
Probably you can have it in your backlog to verify the same.
