### ISSUE TITLE
Target Azure Resource not populating on Code Insiders

### ISSUE THREAD

**Issue by isaacrlevin** [microsoft/vscode-deploy-azure#96]
When I go through the workflow, I am stopped here
![image](https://user-images.githubusercontent.com/8878502/83164012-90b27180-a0c0-11ea-98b7-0104b7fc54c2.png)
The list is blank, even though the api is returning a list per fiddler

![image](https://user-images.githubusercontent.com/8878502/83164136-b8093e80-a0c0-11ea-98ec-82286124ed3b.png)

Let me know if there is additional telemetry you need

**Comment by bishal-pdMSFT** [comment]
@issacnitin can you please take a look

**Comment by issacnitin** [comment]
@isaacrlevin Could you share the template type you choose during the flow, and the resource type you were expecting to see?

**Comment by isaacrlevin** [comment]
I choose Simple Application, and then I get the above, the app is a C# written Azure Function.

**Comment by ItalyPaleAle** [comment]
I am having the same issue with both VS Code 1.45 and VS Code Insiders. The list of resources is empty.

**Comment by ItalyPaleAle** [comment]
I am having the same issue with both VS Code 1.45 and VS Code Insiders. The list of resources is empty.

For me, I'm using a Node.js application and I'm choosing "Node.js with NPM" for Web Apps

**Comment by issacnitin** [comment]
> I choose Simple Application, and then I get the above, the app is a C# written Azure Function.

@isaacrlevin 'Simple Application' option is meant to list only webapps, they won't list functionapps. To list functionapps, you can choose one of the functionapp templates, that should do the trick

@ItalyPaleAle Given you selected the right subscription and you have a webapp in the subscription, it should be listed. Could you let us know the kind of resource you were expecting to see (whether it's functionapp, webapp, aks etc..)

**Comment by ItalyPaleAle** [comment]
I was expecting to see a web app.

**Comment by anuragc617** [comment]
@ItalyPaleAle can you verify that you have a web app in your selected subscription?

**Comment by anuragc617** [comment]
@ItalyPaleAle ping, are you still facing this issue?
